CREATE VIEW TBB_SCHEDULE_VIEW AS
/*
 * TBB_DIVIDEND_INFO: Dividend
 */
-- 기준일 ------------------------------------------------
SELECT BASDT		AS "BASDT"
     , BASDT 		AS "RGHT_DATE"
     , SYMBOL		AS "SYMBOL"
     , RGHT_TP		AS "RGHT_TP"
     , CASE WHEN DIVD_KND = '1' THEN '91'
            WHEN DIVD_KND = '2' THEN '92'
            ELSE '93' END AS "SUB_RGHT_TP"	 
     , '01'			AS "RGHT_DATE_TP"
     , RGHT_CLOS_TP	AS "RGHT_CLOS_TP"
  FROM TBB_DIVIDEND_INFO
 WHERE BASDT > TO_CHAR(ADD_MONTHS(SYSDATE, -6),'YYYYMMDD')
UNION  
-- 주총일 
SELECT BASDT, GNRLMT_DATE, SYMBOL, RGHT_TP
     , CASE WHEN DIVD_KND = '1' THEN '91'
            WHEN DIVD_KND = '2' THEN '92'
            ELSE '93' END	
     , '02', RGHT_CLOS_TP
  FROM TBB_DIVIDEND_INFO	
 WHERE BASDT > TO_CHAR(ADD_MONTHS(SYSDATE, -6),'YYYYMMDD')  
UNION 
-- 권리락일 
SELECT BASDT, EXRGHT_DATE, SYMBOL, RGHT_TP
     , CASE WHEN DIVD_KND = '1' THEN '91'
            WHEN DIVD_KND = '2' THEN '92'
            ELSE '93' END	
     , '03', RGHT_CLOS_TP
  FROM TBB_DIVIDEND_INFO
 WHERE BASDT > TO_CHAR(ADD_MONTHS(SYSDATE, -6),'YYYYMMDD')  
UNION 
-- 현금지급일 
SELECT BASDT, CSH_PAYDT, SYMBOL, RGHT_TP
     , CASE WHEN DIVD_KND = '1' THEN '91'
            WHEN DIVD_KND = '2' THEN '92'
            ELSE '93' END AS "SUB_RGHT_TP"	
     , '04', RGHT_CLOS_TP
  FROM TBB_DIVIDEND_INFO
 WHERE BASDT > TO_CHAR(ADD_MONTHS(SYSDATE, -6),'YYYYMMDD') 
   AND DIVD_KND IN ('1', '3')
UNION 
-- 주식지급일 
SELECT BASDT, STK_PAYDT, SYMBOL, RGHT_TP
     , CASE WHEN DIVD_KND = '1' THEN '91'
            WHEN DIVD_KND = '2' THEN '92'
            ELSE '93' END AS "SUB_RGHT_TP"	
     , '05', RGHT_CLOS_TP
  FROM TBB_DIVIDEND_INFO
 WHERE BASDT > TO_CHAR(ADD_MONTHS(SYSDATE, -6),'YYYYMMDD')  
   AND DIVD_KND IN ('2', '3') 
UNION 
-- 단수주지급일
SELECT BASDT, FRSTK_AMT_PAYDT, SYMBOL, RGHT_TP
     , CASE WHEN DIVD_KND = '1' THEN '91'
            WHEN DIVD_KND = '2' THEN '92'
            ELSE '93' END AS "SUB_RGHT_TP"	
     , '06', RGHT_CLOS_TP
  FROM TBB_DIVIDEND_INFO
 WHERE BASDT > TO_CHAR(ADD_MONTHS(SYSDATE, -6),'YYYYMMDD')  
UNION 
/*
 * TBB_CAPITAL_CHNG_INFO: Capital Increase/Decrease
 */
-- 기준일 ----------------------------------------------------
SELECT BASDT, BASDT, SYMBOL, RGHT_TP, SUB_RGHT_TP, '01', RGHT_CLOS_TP
  FROM TBB_CAPITAL_CHNG_INFO	
 WHERE BASDT > TO_CHAR(ADD_MONTHS(SYSDATE, -6),'YYYYMMDD')  
UNION
-- 주총일
SELECT BASDT, GNRLMT_DATE, SYMBOL, RGHT_TP, SUB_RGHT_TP, '02', RGHT_CLOS_TP
  FROM TBB_CAPITAL_CHNG_INFO	
 WHERE BASDT > TO_CHAR(ADD_MONTHS(SYSDATE, -6),'YYYYMMDD')  
UNION
 -- 권리락일
SELECT BASDT, EXRGHT_DATE, SYMBOL, RGHT_TP, SUB_RGHT_TP, '03', RGHT_CLOS_TP
  FROM TBB_CAPITAL_CHNG_INFO	
 WHERE BASDT > TO_CHAR(ADD_MONTHS(SYSDATE, -6),'YYYYMMDD')  
UNION
-- 단수주지급일 (03: 유상증자, 04: 무상증자, 05: 유상감자, 06:무상감자)
SELECT BASDT, FRSTK_AMT_PAYDT, SYMBOL, RGHT_TP, SUB_RGHT_TP, '06', RGHT_CLOS_TP
  FROM TBB_CAPITAL_CHNG_INFO
 WHERE BASDT > TO_CHAR(ADD_MONTHS(SYSDATE, -6),'YYYYMMDD')  
   AND SUB_RGHT_TP IN ('04', '05', '06')
UNION
-- 청약시작일
SELECT BASDT, SCR_STDT, SYMBOL, RGHT_TP, SUB_RGHT_TP, '07', RGHT_CLOS_TP
  FROM TBB_CAPITAL_CHNG_INFO	
 WHERE BASDT > TO_CHAR(ADD_MONTHS(SYSDATE, -6),'YYYYMMDD')  
UNION
-- 청약종료일
SELECT BASDT, SCR_ENDT, SYMBOL, RGHT_TP, SUB_RGHT_TP, '08', RGHT_CLOS_TP
  FROM TBB_CAPITAL_CHNG_INFO	
 WHERE BASDT > TO_CHAR(ADD_MONTHS(SYSDATE, -6),'YYYYMMDD')  
UNION  
-- 신주인수권거래 시작일
SELECT BASDT, PRGHT_TRAN_STDT, SYMBOL, RGHT_TP, SUB_RGHT_TP, '09', RGHT_CLOS_TP
  FROM TBB_CAPITAL_CHNG_INFO	
 WHERE BASDT > TO_CHAR(ADD_MONTHS(SYSDATE, -6),'YYYYMMDD') 
   AND PRGHT_TRAN_YN = 'Y'
UNION 
-- 신주인수권거래 종료일
SELECT BASDT, PRGHT_TRAN_ENDT, SYMBOL, RGHT_TP, SUB_RGHT_TP, '10', RGHT_CLOS_TP
  FROM TBB_CAPITAL_CHNG_INFO	
 WHERE BASDT > TO_CHAR(ADD_MONTHS(SYSDATE, -6),'YYYYMMDD')  
   AND PRGHT_TRAN_YN = 'Y' 
UNION
-- 유상감자 입금일 (03: 유상증자, 04: 무상증자, 05: 유상감자, 06:무상감자)
SELECT BASDT, DEPO_DATE, SYMBOL, RGHT_TP, SUB_RGHT_TP, '04', RGHT_CLOS_TP
  FROM TBB_CAPITAL_CHNG_INFO	
 WHERE BASDT > TO_CHAR(ADD_MONTHS(SYSDATE, -6),'YYYYMMDD')  
   AND SUB_RGHT_TP IN ('04')
UNION
-- 주식처리일자 (03: 유상증자, 04: 무상증자, 05: 유상감자, 06:무상감자)
SELECT BASDT, STK_PROC_DATE, SYMBOL, RGHT_TP, SUB_RGHT_TP, '05', RGHT_CLOS_TP
  FROM TBB_CAPITAL_CHNG_INFO	
 WHERE BASDT > TO_CHAR(ADD_MONTHS(SYSDATE, -6),'YYYYMMDD')  
UNION
/*
 * TBB_SPLIT_INFO: Stock Split/Reverse Split
 */
-- 기준일 ----------------------------------------------------
SELECT BASDT, BASDT, SYMBOL, RGHT_TP, SUB_RGHT_TP, '01', RGHT_CLOS_TP
  FROM TBB_SPLIT_INFO	
 WHERE BASDT > TO_CHAR(ADD_MONTHS(SYSDATE, -6),'YYYYMMDD')  
UNION
-- 주총일
SELECT BASDT, GNRLMT_DATE, SYMBOL, RGHT_TP, SUB_RGHT_TP, '02', RGHT_CLOS_TP
  FROM TBB_SPLIT_INFO	
 WHERE BASDT > TO_CHAR(ADD_MONTHS(SYSDATE, -6),'YYYYMMDD')  
UNION  
-- 단수주지급일
SELECT BASDT, FRSTK_AMT_PAYDT, SYMBOL, RGHT_TP, SUB_RGHT_TP, '06', RGHT_CLOS_TP
  FROM TBB_SPLIT_INFO	
 WHERE BASDT > TO_CHAR(ADD_MONTHS(SYSDATE, -6),'YYYYMMDD')  
UNION
 -- 액면분할일(12)/병합일(13) SUB_RGHT_TP('11':Stock Split / '12':Reverse Stock Split)
SELECT BASDT, PROC_DATE, SYMBOL, RGHT_TP, SUB_RGHT_TP, TO_CHAR(SUB_RGHT_TP + 1), RGHT_CLOS_TP
  FROM TBB_SPLIT_INFO	
 WHERE BASDT > TO_CHAR(ADD_MONTHS(SYSDATE, -6),'YYYYMMDD')  
UNION
/*
 * TBB_MERGE_INFO: Merge
 */
-- 기준일 ------------------------------------------------
SELECT BASDT, BASDT, SYMBOL, RGHT_TP, '07', '01', RGHT_CLOS_TP
  FROM TBB_MERGE_INFO	
 WHERE BASDT > TO_CHAR(ADD_MONTHS(SYSDATE, -6),'YYYYMMDD')  
UNION
-- 주총일
SELECT BASDT, GNRLMT_DATE, SYMBOL, RGHT_TP, '07', '02', RGHT_CLOS_TP
  FROM TBB_MERGE_INFO	
 WHERE BASDT > TO_CHAR(ADD_MONTHS(SYSDATE, -6),'YYYYMMDD')  
UNION
-- 단수주지급일
SELECT BASDT, FRSTK_AMT_PAYDT, SYMBOL, RGHT_TP, '07', '06', RGHT_CLOS_TP
  FROM TBB_MERGE_INFO	
 WHERE BASDT > TO_CHAR(ADD_MONTHS(SYSDATE, -6),'YYYYMMDD')  
UNION
-- 합병일
SELECT BASDT, MERG_DATE, SYMBOL, RGHT_TP, '07', '11', RGHT_CLOS_TP
  FROM TBB_MERGE_INFO	
 WHERE BASDT > TO_CHAR(ADD_MONTHS(SYSDATE, -6),'YYYYMMDD')  
UNION  
/*
 * TBB_SPIN_OFF_INFO_MSTR: Spin Off
 */
-- 기준일 ------------------------------------------------
SELECT BASDT, BASDT, SYMBOL, RGHT_TP, '08', '01', RGHT_CLOS_TP
  FROM TBB_SPIN_OFF_INFO_MSTR	
 WHERE BASDT > TO_CHAR(ADD_MONTHS(SYSDATE, -6),'YYYYMMDD')  
UNION
-- 주총일
SELECT BASDT, GNRLMT_DATE, SYMBOL, RGHT_TP, '08', '02', RGHT_CLOS_TP
  FROM TBB_SPIN_OFF_INFO_MSTR	
 WHERE BASDT > TO_CHAR(ADD_MONTHS(SYSDATE, -6),'YYYYMMDD')  
UNION
-- 단수주지급일
SELECT BASDT, FRSTK_AMT_PAYDT, SYMBOL, RGHT_TP, '08', '06', RGHT_CLOS_TP
  FROM TBB_SPIN_OFF_INFO_MSTR	
 WHERE BASDT > TO_CHAR(ADD_MONTHS(SYSDATE, -6),'YYYYMMDD')  
UNION
-- 회사분할일
SELECT BASDT, PROC_DATE, SYMBOL, RGHT_TP, '08', '14', RGHT_CLOS_TP
  FROM TBB_SPIN_OFF_INFO_MSTR
 WHERE BASDT > TO_CHAR(ADD_MONTHS(SYSDATE, -6),'YYYYMMDD');





CREATE VIEW TBB_FIXDATE_VIEW AS
/*
 * TBB_DIVIDEND_INFO: Dividend
 */
-- 기준일 ------------------------------------------------
SELECT BASDT 		AS "BASDT"
     , SYMBOL		AS "SYMBOL"
     , RGHT_TP		AS "RGHT_TP"
     , CASE WHEN DIVD_KND = '1' THEN '91'
            WHEN DIVD_KND = '2' THEN '92'
            ELSE '93' END AS "SUB_RGHT_TP"
     , RGHT_CLOS_TP AS "RGHT_CLOS_TP"
     , 'N'			AS "PRGHT_TRAN_YN"
  FROM TBB_DIVIDEND_INFO
 WHERE BASDT > TO_CHAR(ADD_MONTHS(SYSDATE, -6),'YYYYMMDD')  
UNION  
/*
 * TBB_CAPITAL_CHNG_INFO: Capital Increase/Decrease
 */
-- 기준일 ----------------------------------------------------
SELECT BASDT, SYMBOL, RGHT_TP, SUB_RGHT_TP, RGHT_CLOS_TP, PRGHT_TRAN_YN
  FROM TBB_CAPITAL_CHNG_INFO	
 WHERE BASDT > TO_CHAR(ADD_MONTHS(SYSDATE, -6),'YYYYMMDD')  
UNION
/*
 * TBB_SPLIT_INFO: Stock Split/Reverse Split
 */
-- 기준일 ----------------------------------------------------
SELECT BASDT, SYMBOL, RGHT_TP, SUB_RGHT_TP, RGHT_CLOS_TP, 'N'
  FROM TBB_SPLIT_INFO	
 WHERE BASDT > TO_CHAR(ADD_MONTHS(SYSDATE, -6),'YYYYMMDD')  
UNION
/*
 * TBB_MERGE_INFO: Merge
 */
-- 기준일 ------------------------------------------------
SELECT BASDT, SYMBOL, RGHT_TP, '07', RGHT_CLOS_TP, 'N'
  FROM TBB_MERGE_INFO	
 WHERE BASDT > TO_CHAR(ADD_MONTHS(SYSDATE, -6),'YYYYMMDD')  
UNION/*
 * TBB_SPIN_OFF_INFO_MSTR: Spin Off
 */
-- 기준일 ------------------------------------------------
SELECT BASDT, SYMBOL, RGHT_TP, '08', RGHT_CLOS_TP, 'N'
  FROM TBB_SPIN_OFF_INFO_MSTR
 WHERE BASDT > TO_CHAR(ADD_MONTHS(SYSDATE, -6),'YYYYMMDD');


