DROP TABLE TBB_CAPITAL_CHNG_INFO;
CREATE TABLE TBB_CAPITAL_CHNG_INFO(
    BASDT          VARCHAR2(8)    NOT NULL,
    SYMBOL          VARCHAR2(12)    NOT NULL,
    RGHT_TP          VARCHAR2(2)    NOT NULL,
    SUB_RGHT_TP          VARCHAR2(2),
    GNRLMT_DATE          VARCHAR2(8),
    EXRGHT_DATE          VARCHAR2(8),
    FVAL          NUMBER    DEFAULT '0'    NOT NULL,
    POSS_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    RGHT_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    RGHT_POSS_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    ALOC_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    CMSTK_ISUPRC          NUMBER    DEFAULT '0'    NOT NULL,
    CMSTK_ROC_PRC          NUMBER    DEFAULT '0'    NOT NULL,
    CMSTK_FRSTK_RFPRC          NUMBER    DEFAULT '0'    NOT NULL,
    CMSTK_LIST_STK_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    SCR_STDT          VARCHAR2(8),
    SCR_ENDT          VARCHAR2(8),
    FRSTK_AMT_PAYDT          VARCHAR2(8),
    WAIT_YN          VARCHAR2(1),
    TRAN_AVAL_DATE          VARCHAR2(8),
    DEPO_DATE          VARCHAR2(8),
    STK_PROC_DATE          VARCHAR2(8),
    LISTDT          VARCHAR2(8),
    GRTS_ICAP_FRSC_TP          VARCHAR2(1),
    TXRT          NUMBER    DEFAULT '0'    NOT NULL,
    RGHT_WTHD_TP          VARCHAR2(1)    DEFAULT '1'    NOT NULL,
    SE_PROC_TMP          NUMBER,
    SE_TRGT_CNT          NUMBER    DEFAULT '0'    NOT NULL,
    SE_PROC_CNT          NUMBER    DEFAULT '0'    NOT NULL,
    CSH_PROC_TMP          NUMBER,
    CSH_TRGT_CNT          NUMBER    DEFAULT '0'    NOT NULL,
    CSH_PROC_CNT          NUMBER    DEFAULT '0'    NOT NULL,
    FRSTK_PROC_TMP          NUMBER,
    FRSTK_TRGT_CNT          NUMBER    DEFAULT '0'    NOT NULL,
    FRSTK_PROC_CNT          NUMBER    DEFAULT '0'    NOT NULL,
    PRGHT_TRAN_YN          VARCHAR2(1),
    PRGHT_TRAN_STDT          VARCHAR2(8),
    PRGHT_TRAN_ENDT          VARCHAR2(8),
    RGHT_PRGHT_APRV_APLC_DATE          VARCHAR2(8),
    RGHT_PRGHT_APRV_APLC_SEQ          NUMBER,
    RGHT_PRGHT_APRV_BIZ_CODE          VARCHAR2(3),
    RGHT_SE_APRV_APLC_DATE          VARCHAR2(8),
    RGHT_SE_APRV_APLC_SEQ          NUMBER,
    RGHT_SE_APRV_BIZ_CODE          VARCHAR2(3),
    RGHT_CSH_APRV_APLC_DATE          VARCHAR2(8),
    RGHT_CSH_APRV_APLC_SEQ          NUMBER,
    RGHT_CSH_APRV_BIZ_CODE          VARCHAR2(3),
    FRSTK_AMT_APRV_APLC_DATE          VARCHAR2(8),
    FRSTK_AMT_APRV_APLC_SEQ          NUMBER,
    FRSTK_AMT_APRV_BIZ_CODE          VARCHAR2(3),
    SCHD_CONF_YN          VARCHAR2(1),
    RGHT_CLOS_TP          VARCHAR2(1),
    RMRK          VARCHAR2(300),
    WRKR_ID          VARCHAR2(20),
    WRK_TMP          NUMBER,
PRIMARY KEY(BASDT,SYMBOL)
);


DROP TABLE TBB_CAPITAL_CHNG_SCHD;
CREATE TABLE TBB_CAPITAL_CHNG_SCHD(
    BASDT          VARCHAR2(8)    NOT NULL,
    SYMBOL          VARCHAR2(12)    NOT NULL,
    ACNT_NO          VARCHAR2(8)    NOT NULL,
    SUB_ACNT_NO          VARCHAR2(9)    NOT NULL,
    RGHT_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    ROC_AMT          NUMBER    DEFAULT '0'    NOT NULL,
    FRSTK_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    FRSTK_AMT          NUMBER    DEFAULT '0'    NOT NULL,
    RGHT_BUY_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    RGHT_SEL_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    SCR_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    ROC_WIDR_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    RGHT_DEPO_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    SE_WIDR_TRAN_DATE          VARCHAR2(8),
    SE_WIDR_TRAN_NO          NUMBER    DEFAULT '0'    NOT NULL,
    CSH_DEPO_TRAN_DATE          VARCHAR2(8),
    CSH_DEPO_TRAN_NO          NUMBER    DEFAULT '0'    NOT NULL,
    SE_DEPO_TRAN_DATE          VARCHAR2(8),
    SE_DEPO_TRAN_NO          NUMBER    DEFAULT '0'    NOT NULL,
    FRSTK_ATM_TRAN_DATE          VARCHAR2(8),
    FRSTK_ATM_TRAN_NO          NUMBER    DEFAULT '0'    NOT NULL,
    WRKR_ID          VARCHAR2(20),
    WRK_TMP          NUMBER,
PRIMARY KEY(BASDT,SYMBOL,ACNT_NO,SUB_ACNT_NO)
);



DROP TABLE TBB_DIVIDEND_INFO;
CREATE TABLE TBB_DIVIDEND_INFO(
    BASDT          VARCHAR2(8)    NOT NULL,
    SYMBOL          VARCHAR2(12)    NOT NULL,
    RGHT_TP          VARCHAR2(2)    NOT NULL,
    GNRLMT_DATE          VARCHAR2(8),
    EXRGHT_DATE          VARCHAR2(8),
    FVAL          NUMBER    DEFAULT '0'    NOT NULL,
    DIVD_KND          VARCHAR2(1),
    CSH_DIVD_TP          VARCHAR2(1),
    CMSTK_CSH_DIVD_RT          NUMBER    DEFAULT '0'    NOT NULL,
    CMSTK_CSH_DIVD_AMT          NUMBER    DEFAULT '0'    NOT NULL,
    POSS_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    ALOC_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    CMSTK_FRSTK_RFPRC          NUMBER    DEFAULT '0'    NOT NULL,
    CSH_PAYDT          VARCHAR2(8),
    STK_PAYDT          VARCHAR2(8),
    FRSTK_AMT_PAYDT          VARCHAR2(8),
    WAIT_YN          VARCHAR2(1),
    TRAN_AVAL_DATE          VARCHAR2(8),
    TXRT          NUMBER    DEFAULT '0'    NOT NULL,
    RGHT_WTHD_TP          VARCHAR2(1)    DEFAULT '1'    NOT NULL,
    SE_PROC_TMP          NUMBER,
    SE_TRGT_CNT          NUMBER    DEFAULT '0'    NOT NULL,
    SE_PROC_CNT          NUMBER    DEFAULT '0'    NOT NULL,
    CSH_PROC_TMP          NUMBER,
    CSH_TRGT_CNT          NUMBER    DEFAULT '0'    NOT NULL,
    CSH_PROC_CNT          NUMBER    DEFAULT '0'    NOT NULL,
    FRSTK_PROC_TMP          NUMBER,
    FRSTK_TRGT_CNT          NUMBER    DEFAULT '0'    NOT NULL,
    FRSTK_PROC_CNT          NUMBER    DEFAULT '0'    NOT NULL,
    RGHT_SE_APRV_APLC_DATE          VARCHAR2(8),
    RGHT_SE_APRV_APLC_SEQ          NUMBER,
    RGHT_SE_APRV_BIZ_CODE          VARCHAR2(3),
    RGHT_CSH_APRV_APLC_DATE          VARCHAR2(8),
    RGHT_CSH_APRV_APLC_SEQ          NUMBER,
    RGHT_CSH_APRV_BIZ_CODE          VARCHAR2(3),
    FRSTK_AMT_APRV_APLC_DATE          VARCHAR2(8),
    FRSTK_AMT_APRV_APLC_SEQ          NUMBER,
    FRSTK_AMT_APRV_BIZ_CODE          VARCHAR2(3),
    SCHD_CONF_YN          VARCHAR2(1),
    RGHT_CLOS_TP          VARCHAR2(1),
    RMRK          VARCHAR2(300),
    WRKR_ID          VARCHAR2(20),
    WRK_TMP          NUMBER,
PRIMARY KEY(BASDT,SYMBOL)
);



DROP TABLE TBB_DIVIDEND_SCHD;
CREATE TABLE TBB_DIVIDEND_SCHD(
    BASDT          VARCHAR2(8)    NOT NULL,
    SYMBOL          VARCHAR2(12)    NOT NULL,
    ACNT_NO          VARCHAR2(8)    NOT NULL,
    SUB_ACNT_NO          VARCHAR2(9)    NOT NULL,
    DIVD_CSH_AMT          NUMBER    DEFAULT '0'    NOT NULL,
    DIVD_STK_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    FRSTK_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    FRSTK_AMT          NUMBER    DEFAULT '0'    NOT NULL,
    CSH_DEPO_TRAN_DATE          VARCHAR2(8),
    CSH_DEPO_TRAN_NO          NUMBER    DEFAULT '0'    NOT NULL,
    SE_DEPO_TRAN_DATE          VARCHAR2(8),
    SE_DEPO_TRAN_NO          NUMBER    DEFAULT '0'    NOT NULL,
    FRSTK_ATM_TRAN_DATE          VARCHAR2(8),
    FRSTK_ATM_TRAN_NO          NUMBER    DEFAULT '0'    NOT NULL,
    WRKR_ID          VARCHAR2(20),
    WRK_TMP          NUMBER,
PRIMARY KEY(BASDT,SYMBOL,ACNT_NO,SUB_ACNT_NO)
);



DROP TABLE TBB_ICAP_RIGHT_TRADE_DTL;
CREATE TABLE TBB_ICAP_RIGHT_TRADE_DTL(
    TRD_DATE          VARCHAR2(8)    NOT NULL,
    TRD_SEQ          NUMBER    NOT NULL,
    APRV_BIZ_CODE          VARCHAR2(3)    NOT NULL,
    BASDT          VARCHAR2(8)    NOT NULL,
    SYMBOL          VARCHAR2(12)    NOT NULL,
    ACNT_NO          VARCHAR2(8)    NOT NULL,
    SUB_ACNT_NO          VARCHAR2(9)    NOT NULL,
    BUY_SEL_TP          VARCHAR2(1),
    TRD_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    TRD_AMT          NUMBER    DEFAULT '0'    NOT NULL,
    TRD_FEE          NUMBER    DEFAULT '0'    NOT NULL,
    PTNR_ACNT_NO          VARCHAR2(8),
    PTNR_SUB_ACNT_NO          VARCHAR2(9),
    TRAN_PTNR_ID_KND          VARCHAR2(1),
    TRAN_PTNR_ID          VARCHAR2(20),
    TRAN_PTNR_NM          VARCHAR2(50),
    VSD_MUR          VARCHAR2(16),
    VSD_MIR          VARCHAR2(28),
    TRAN_DATE          VARCHAR2(8),
    TRAN_SEQ          NUMBER    DEFAULT '0'    NOT NULL,
    TRD_CNCL_YN          VARCHAR2(1),
    CNCL_PRSN_ID          VARCHAR2(20),
    CNCL_TMP          NUMBER,
    RMRK          VARCHAR2(300),
    WRKR_ID          VARCHAR2(20),
    WRK_TMP          NUMBER,
PRIMARY KEY(TRD_DATE,TRD_SEQ)
);



DROP TABLE TBB_ICAP_SUBSCRIPTION_DTL;
CREATE TABLE TBB_ICAP_SUBSCRIPTION_DTL(
    BASDT          VARCHAR2(8)    NOT NULL,
    SYMBOL          VARCHAR2(12)    NOT NULL,
    SCR_DATE          VARCHAR2(8)    NOT NULL,
    SCR_SEQ          NUMBER    NOT NULL,
    ACNT_NO          VARCHAR2(8)    NOT NULL,
    SUB_ACNT_NO          VARCHAR2(9)    NOT NULL,
    SCR_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    SCR_AMT          NUMBER    DEFAULT '0'    NOT NULL,
    SCR_FEE          NUMBER    DEFAULT '0'    NOT NULL,
    SCR_CSH_AMT          NUMBER    DEFAULT '0'    NOT NULL,
    SCR_LOAN_AMT          NUMBER    DEFAULT '0'    NOT NULL,
    APRV_BIZ_CODE          VARCHAR2(3),
    APRV_APLC_DT          VARCHAR2(8),
    APRV_APLC_SEQ          NUMBER,
    SCR_CNCL_YN          VARCHAR2(1),
    CNCL_PRSN_ID          VARCHAR2(20),
    CNCL_TMP          NUMBER,
    RMRK          VARCHAR2(300),
    WRKR_ID          VARCHAR2(20),
    WRK_TMP          NUMBER,
PRIMARY KEY(BASDT,SYMBOL,SCR_DATE,SCR_SEQ)
);



DROP TABLE TBB_MERGE_INFO;
CREATE TABLE TBB_MERGE_INFO(
    BASDT          VARCHAR2(8)    NOT NULL,
    SYMBOL          VARCHAR2(12)    NOT NULL,
    RGHT_TP          VARCHAR2(2)    NOT NULL,
    GNRLMT_DATE          VARCHAR2(8),
    MERG_DATE          VARCHAR2(8),
    AFCHNG_SYMBOL          VARCHAR2(12)    NOT NULL,
    POSS_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    ALOC_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    FRSTK_RFPRC          NUMBER    DEFAULT '0'    NOT NULL,
    FRSTK_AMT_PAYDT          VARCHAR2(8),
    WAIT_YN          VARCHAR2(1),
    TRAN_AVAL_DATE          VARCHAR2(8),
    SE_PROC_TMP          NUMBER,
    SE_TRGT_CNT          NUMBER    DEFAULT '0',
    SE_PROC_CNT          NUMBER    DEFAULT '0',
    FRSTK_PROC_TMP          NUMBER,
    FRSTK_TRGT_CNT          NUMBER    DEFAULT '0',
    FRSTK_PROC_CNT          NUMBER    DEFAULT '0',
    RGHT_SE_APRV_APLC_DATE          VARCHAR2(8),
    RGHT_SE_APRV_APLC_SEQ          NUMBER,
    RGHT_SE_APRV_BIZ_CODE          VARCHAR2(3),
    FRSTK_AMT_APRV_APLC_DATE          VARCHAR2(8),
    FRSTK_AMT_APRV_APLC_SEQ          NUMBER,
    FRSTK_AMT_APRV_BIZ_CODE          VARCHAR2(3),
    SCHD_CONF_YN          VARCHAR2(1),
    RGHT_CLOS_TP          VARCHAR2(1),
    RMRK          VARCHAR2(300),
    WRKR_ID          VARCHAR2(20),
    WRK_TMP          NUMBER,
CONSTRAINT TBB_MERGE_INFO_PK PRIMARY KEY(BASDT,SYMBOL)
);



DROP TABLE TBB_RIGHTS_APRV_APLC_DTL;
CREATE TABLE TBB_RIGHTS_APRV_APLC_DTL(
    APRV_APLC_DATE          VARCHAR2(8)    NOT NULL,
    APRV_APLC_SEQ          NUMBER    NOT NULL,
    APRV_BIZ_CODE          VARCHAR2(3)    NOT NULL,
    BASDT          VARCHAR2(8)    NOT NULL,
    SYMBOL          VARCHAR2(12)    NOT NULL,
    WRKR_ID          VARCHAR2(20),
    WRK_TMP          NUMBER,
PRIMARY KEY(APRV_APLC_DATE,APRV_APLC_SEQ)
);



DROP TABLE TBB_RIGHTS_CLOSE_DTL;
CREATE TABLE TBB_RIGHTS_CLOSE_DTL(
    BASDT          VARCHAR2(8)    NOT NULL,
    SYMBOL          VARCHAR2(12)    NOT NULL,
    RGHT_TP          VARCHAR2(2)    NOT NULL,
    DEPO_PROC_STAT_TP          VARCHAR2(1),
    SE_DEPO_PROC_STAT_TP          VARCHAR2(1),
    SE_WIDR_PROC_STAT_TP          VARCHAR2(1),
    FRSTK_AMT_PROC_STAT_TP          VARCHAR2(1),
    RGHT_CLOS_TP          VARCHAR2(1),
    WRKR_ID          VARCHAR2(20),
    WRK_TMP          NUMBER,
PRIMARY KEY(BASDT,SYMBOL,RGHT_TP)
);



DROP TABLE TBB_SPIN_OFF_INFO_DETL;
CREATE TABLE TBB_SPIN_OFF_INFO_DETL(
    BASDT          VARCHAR2(8)    NOT NULL,
    SYMBOL          VARCHAR2(12)    NOT NULL,
    LIST_SYMBOL          VARCHAR2(12)    NOT NULL,
    DIV_RT          NUMBER    DEFAULT '0'    NOT NULL,
    FVAL          NUMBER    DEFAULT '0'    NOT NULL,
    LIST_STK_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    SE_PROC_TMP          NUMBER,
    SE_TRGT_CNT          NUMBER    DEFAULT '0'    NOT NULL,
    SE_PROC_CNT          NUMBER    DEFAULT '0'    NOT NULL,
    FRSTK_PROC_TMP          NUMBER,
    FRSTK_TRGT_CNT          NUMBER    DEFAULT '0'    NOT NULL,
    FRSTK_PROC_CNT          NUMBER    DEFAULT '0'    NOT NULL,
    WRKR_ID          VARCHAR2(20),
    WRK_TMP          NUMBER,
PRIMARY KEY(BASDT,SYMBOL,LIST_SYMBOL)
);



DROP TABLE TBB_SPIN_OFF_INFO_MSTR;
CREATE TABLE TBB_SPIN_OFF_INFO_MSTR(
    BASDT          VARCHAR2(8)    NOT NULL,
    SYMBOL          VARCHAR2(12)    NOT NULL,
    RGHT_TP          VARCHAR2(2)    NOT NULL,
    GNRLMT_DATE          VARCHAR2(8),
    CNTN_RT          NUMBER    DEFAULT '0'    NOT NULL,
    PROC_DATE          VARCHAR2(8),
    CMSTK_FRSTK_RFPRC          NUMBER    DEFAULT '0'    NOT NULL,
    FRSTK_AMT_PAYDT          VARCHAR2(8),
    WAIT_YN          VARCHAR2(1),
    TRAN_AVAL_DATE          VARCHAR2(8),
    BFCHNG_CMSTK_LIST_STK_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    AFCHNG_CMSTK_LIST_STK_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    RGHT_SE_APRV_APLC_DATE          VARCHAR2(8),
    RGHT_SE_APRV_APLC_SEQ          NUMBER,
    RGHT_SE_APRV_BIZ_CODE          VARCHAR2(3),
    FRSTK_AMT_APRV_APLC_DATE          VARCHAR2(8),
    FRSTK_AMT_APRV_APLC_SEQ          NUMBER,
    FRSTK_AMT_APRV_BIZ_CODE          VARCHAR2(3),
    SCHD_CONF_YN          VARCHAR2(1),
    RGHT_CLOS_TP          VARCHAR2(1),
    RMRK          VARCHAR2(300),
    WRKR_ID          VARCHAR2(20),
    WRK_TMP          NUMBER,
PRIMARY KEY(BASDT,SYMBOL)
);



DROP TABLE TBB_SPIN_OFF_SCHD;
CREATE TABLE TBB_SPIN_OFF_SCHD(
    BASDT          VARCHAR2(8)    NOT NULL,
    SYMBOL          VARCHAR2(12)    NOT NULL,
    ACNT_NO          VARCHAR2(8)    NOT NULL,
    SUB_ACNT_NO          VARCHAR2(9)    NOT NULL,
    AFCHNG_SYMBOL          VARCHAR2(12)    NOT NULL,
    BFCHNG_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    AFCHNG_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    FRSTK_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    FRSTK_AMT          NUMBER    DEFAULT '0'    NOT NULL,
    TRAN_DATE          VARCHAR2(8),
    TRAN_NO          NUMBER    DEFAULT '0'    NOT NULL,
    FRSTK_ATM_TRAN_DATE          VARCHAR2(8),
    FRSTK_ATM_TRAN_NO          NUMBER    DEFAULT '0'    NOT NULL,
    WRKR_ID          VARCHAR2(20),
    WRK_TMP          NUMBER,
PRIMARY KEY(BASDT,SYMBOL,ACNT_NO,SUB_ACNT_NO,AFCHNG_SYMBOL)
);



DROP TABLE TBB_SPLIT_INFO;
CREATE TABLE TBB_SPLIT_INFO(
    BASDT          VARCHAR2(8)    NOT NULL,
    SYMBOL          VARCHAR2(12)    NOT NULL,
    RGHT_TP          VARCHAR2(2)    NOT NULL,
    SUB_RGHT_TP          VARCHAR2(2)    NOT NULL,
    POSS_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    ALOC_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    GNRLMT_DATE          VARCHAR2(8),
    PROC_DATE          VARCHAR2(8),
    FVAL          NUMBER    DEFAULT '0'    NOT NULL,
    AFCHNG_FVAL          NUMBER    DEFAULT '0'    NOT NULL,
    CMSTK_FRSTK_RFPRC          NUMBER    DEFAULT '0'    NOT NULL,
    FRSTK_AMT_PAYDT          VARCHAR2(8),
    WAIT_YN          VARCHAR2(1),
    TRAN_AVAL_DATE          VARCHAR2(8),
    SE_PROC_TMP          NUMBER,
    SE_TRGT_CNT          NUMBER    DEFAULT '0'    NOT NULL,
    SE_PROC_CNT          NUMBER    DEFAULT '0'    NOT NULL,
    FRSTK_PROC_TMP          NUMBER,
    FRSTK_TRGT_CNT          NUMBER    DEFAULT '0'    NOT NULL,
    FRSTK_PROC_CNT          NUMBER    DEFAULT '0'    NOT NULL,
    RGHT_SE_APRV_APLC_DATE          VARCHAR2(8),
    RGHT_SE_APRV_APLC_SEQ          NUMBER,
    RGHT_SE_APRV_BIZ_CODE          VARCHAR2(3),
    FRSTK_AMT_APRV_APLC_DATE          VARCHAR2(8),
    FRSTK_AMT_APRV_APLC_SEQ          NUMBER,
    FRSTK_AMT_APRV_BIZ_CODE          VARCHAR2(3),
    SCHD_CONF_YN          VARCHAR2(1),
    RGHT_CLOS_TP          VARCHAR2(1),
    RMRK          VARCHAR2(300),
    WRKR_ID          VARCHAR2(20),
    WRK_TMP          NUMBER,
PRIMARY KEY(BASDT,SYMBOL)
);



DROP TABLE TBB_STOCK_CHNG_SCHD;
CREATE TABLE TBB_STOCK_CHNG_SCHD(
    BASDT          VARCHAR2(8)    NOT NULL,
    SYMBOL          VARCHAR2(12)    NOT NULL,
    ACNT_NO          VARCHAR2(8)    NOT NULL,
    SUB_ACNT_NO          VARCHAR2(9)    NOT NULL,
    AFCHNG_SYMBOL          VARCHAR2(12)    NOT NULL,
    BFCHNG_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    AFCHNG_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    FRSTK_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    FRSTK_AMT          NUMBER    DEFAULT '0'    NOT NULL,
    SE_WIDR_TRAN_DATE          VARCHAR2(8),
    SE_WIDR_TRAN_NO          NUMBER    DEFAULT '0'    NOT NULL,
    SE_DEPO_TRAN_DATE          VARCHAR2(8),
    SE_DEPO_TRAN_NO          NUMBER    DEFAULT '0'    NOT NULL,
    FRSTK_ATM_TRAN_DATE          VARCHAR2(8),
    FRSTK_ATM_TRAN_NO          NUMBER    DEFAULT '0'    NOT NULL,
    WRKR_ID          VARCHAR2(20),
    WRK_TMP          NUMBER,
PRIMARY KEY(BASDT,SYMBOL,ACNT_NO,SUB_ACNT_NO,AFCHNG_SYMBOL)
);



DROP TABLE TBB_VSDACCT_BASE_DATE_BALANCE;
CREATE TABLE TBB_VSDACCT_BASE_DATE_BALANCE(
    BASDT          VARCHAR2(8)    NOT NULL,
    SYMBOL          VARCHAR2(12)    NOT NULL,
    VSD_ACNT_NO          VARCHAR2(10)    NOT NULL,
    SETL_BAL_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    WRKR_ID          VARCHAR2(20),
    WRK_TMP          NUMBER,
PRIMARY KEY(BASDT,SYMBOL,VSD_ACNT_NO)
);



DROP TABLE TBB_VSDACCT_CAPITAL_CHNG_SCHD;
CREATE TABLE TBB_VSDACCT_CAPITAL_CHNG_SCHD(
    BASDT          VARCHAR2(8)    NOT NULL,
    SYMBOL          VARCHAR2(12)    NOT NULL,
    VSD_ACNT_NO          VARCHAR2(10)    NOT NULL,
    RGHT_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    ROC_AMT          NUMBER    DEFAULT '0'    NOT NULL,
    FRSTK_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    FRSTK_AMT          NUMBER    DEFAULT '0'    NOT NULL,
    RGHT_BUY_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    RGHT_SEL_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    SCR_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    ROC_WIDR_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    RGHT_DEPO_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    VSD_RGHT_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    VSD_ROC_AMT          NUMBER    DEFAULT '0'    NOT NULL,
    VSD_FRSTK_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    VSD_FRSTK_AMT          NUMBER    DEFAULT '0'    NOT NULL,
    VSD_RGHT_BUY_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    VSD_RGHT_SEL_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    VSD_SCR_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    VSD_ROC_WIDR_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    VSD_RGHT_DEPO_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    WRKR_ID          VARCHAR2(20),
    WRK_TMP          NUMBER,
PRIMARY KEY(BASDT,SYMBOL,VSD_ACNT_NO)
);



DROP TABLE TBB_VSDACCT_DIVIDEND_SCHD;
CREATE TABLE TBB_VSDACCT_DIVIDEND_SCHD(
    BASDT          VARCHAR2(8)    NOT NULL,
    SYMBOL          VARCHAR2(12)    NOT NULL,
    VSD_ACNT_NO          VARCHAR2(10)    NOT NULL,
    DIVD_CSH_AMT          NUMBER    DEFAULT '0'    NOT NULL,
    DIVD_STK_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    FRSTK_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    FRSTK_AMT          NUMBER    DEFAULT '0'    NOT NULL,
    VSD_DIVD_CSH_AMT          NUMBER    DEFAULT '0'    NOT NULL,
    VSD_DIVD_STK_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    VSD_FRSTK_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    VSD_FRSTK_AMT          NUMBER    DEFAULT '0'    NOT NULL,
    WRKR_ID          VARCHAR2(20),
    WRK_TMP          NUMBER,
PRIMARY KEY(BASDT,SYMBOL,VSD_ACNT_NO)
);



DROP TABLE TBB_VSDACCT_SPIN_OFF_SCHD;
CREATE TABLE TBB_VSDACCT_SPIN_OFF_SCHD(
    BASDT          VARCHAR2(8)    NOT NULL,
    SYMBOL          VARCHAR2(12)    NOT NULL,
    VSD_ACNT_NO          VARCHAR2(10)    NOT NULL,
    AFCHNG_SYMBOL          VARCHAR2(12)    NOT NULL,
    BFCHNG_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    AFCHNG_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    FRSTK_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    FRSTK_AMT          NUMBER    DEFAULT '0'    NOT NULL,
    VSD_BFCHNG_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    VSD_AFCHNG_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    VSD_FRSTK_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    VSD_FRSTK_AMT          NUMBER    DEFAULT '0'    NOT NULL,
    WRKR_ID          VARCHAR2(20),
    WRK_TMP          NUMBER,
PRIMARY KEY(BASDT,SYMBOL,VSD_ACNT_NO,AFCHNG_SYMBOL)
);

DROP TABLE TBB_SPIN_OFF_INFO_MSTR;
CREATE TABLE TBB_SPIN_OFF_INFO_MSTR(
    BASDT          VARCHAR2(8)    NOT NULL,
    SYMBOL          VARCHAR2(12)    NOT NULL,
    RGHT_TP          VARCHAR2(2)    NOT NULL,
    GNRLMT_DATE          VARCHAR2(8),
    CNTN_RT          NUMBER    DEFAULT '0'    NOT NULL,
    FVAL          NUMBER    DEFAULT '0'    NOT NULL,
    PROC_DATE          VARCHAR2(8),
    CMSTK_FRSTK_RFPRC          NUMBER    DEFAULT '0'    NOT NULL,
    FRSTK_AMT_PAYDT          VARCHAR2(8),
    WAIT_YN          VARCHAR2(1),
    TRAN_AVAL_DATE          VARCHAR2(8),
    BFCHNG_CMSTK_LIST_STK_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    AFCHNG_CMSTK_LIST_STK_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    RGHT_SE_APRV_APLC_DATE          VARCHAR2(8),
    RGHT_SE_APRV_APLC_SEQ          NUMBER,
    RGHT_SE_APRV_BIZ_CODE          VARCHAR2(3),
    FRSTK_AMT_APRV_APLC_DATE          VARCHAR2(8),
    FRSTK_AMT_APRV_APLC_SEQ          NUMBER,
    FRSTK_AMT_APRV_BIZ_CODE          VARCHAR2(3),
    SCHD_CONF_YN          VARCHAR2(1),
    RGHT_CLOS_TP          VARCHAR2(1),
    RMRK          VARCHAR2(300),
    WRKR_ID          VARCHAR2(20),
    WRK_TMP          NUMBER,
PRIMARY KEY(BASDT,SYMBOL)
);

DROP TABLE TBB_VSDACCT_STOCK_CHNG_SCHD;
CREATE TABLE TBB_VSDACCT_STOCK_CHNG_SCHD(
    BASDT          VARCHAR2(8)    NOT NULL,
    SYMBOL          VARCHAR2(12)    NOT NULL,
    VSD_ACNT_NO          VARCHAR2(10)    NOT NULL,
    AFCHNG_SYMBOL          VARCHAR2(12)    NOT NULL,
    BFCHNG_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    AFCHNG_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    FRSTK_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    FRSTK_AMT          NUMBER    DEFAULT '0'    NOT NULL,
    VSD_BFCHNG_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    VSD_AFCHNG_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    VSD_FRSTK_QTY          NUMBER    DEFAULT '0'    NOT NULL,
    VSD_FRSTK_AMT          NUMBER    DEFAULT '0'    NOT NULL,
    WRKR_ID          VARCHAR2(20),
    WRK_TMP          NUMBER,
PRIMARY KEY(BASDT,SYMBOL,VSD_ACNT_NO,AFCHNG_SYMBOL)
);

